# Find RabbitMQ-C
# Merder Kim <hoxnox@gmail.com>
#
#  input:
#  RABBITMQ_ROOT
#
#  output:
#  RABBITMQ_FOUND
#  RABBOTMQ_INCLUDE_DIR
#  RABBITMQ_LIBRARIES
#

if(RABBITMQ_INCLUDE_DIR AND RABBITMQ_LIBRARIES)
    set(RABBITMQ_FIND_QUIETLY TRUE) # cached
endif(RABBITMQ_INCLUDE_DIR AND RABBITMQ_LIBRARIES)

if(NOT DEFINED RABBITMQ_ROOT)
    set (RABBITMQ_ROOT /usr /usr/local $ENV{RABBITMQ_ROOT} )
endif(NOT DEFINED RABBITMQ_ROOT)

find_path(RABBITMQ_INCLUDE_DIR amqp.h
    PATHS ${RABBITMQ_ROOT}
    PATH_SUFFIXES amqp/include include
)

find_library(RABBITMQ_LIBRARY
    NAMES rabbitmq
    PATHS ${RABBITMQ_ROOT}
    PATH_SUFFIXES lib
)

set(RABBITMQ_LIBRARIES ${RABBITMQ_LIBRARY})

mark_as_advanced(RABBITMQ_INCLUDE_DIR RABBITMQ_LIBRARIES)

include("${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake")
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RABBITMQ DEFAULT_MSG RABBITMQ_INCLUDE_DIR RABBITMQ_LIBRARIES)

